[context.deploy-preview.environment]
  HUGO_VERSION = "0.111.2"

[context.production.environment]
  HUGO_VERSION = "0.111.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[build]
  publish = "public"
  command = "hugo -s /opt/build/repo/zeroatthebone.us --gc --minify"

[context.split1]
  command = "cd zeroatthebone.us; hugo --gc --minify --enableGitInfo"

[context.split1.environment]
  HUGO_VERSION = "0.111.2"
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "cd zeroatthebone.us; hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"


[context.branch-deploy]
  command = "hugo -s /opt/build/repo/zeroatthebone.us --gc --minify -D -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.111.2"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/npmjs/*"
  to = "/npmjs/"
  status = 200

[taxonomies]
  topic = 'topics'