[context.deploy-preview.environment]
  HUGO_VERSION = "0.161.1"
  
[context.production.environment]
  HUGO_VERSION = "0.161.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[build]
  publish = "public"
  command = "hugo -s /opt/build/repo/zeroatthebone.us --gc --minify"

[context.split1]
  command = "cd zeroatthebone.us; hugo --gc --minify --enableGitInfo"

[context.split1.environment]
  HUGO_VERSION = "0.161.1"
  HUGO_ENV = "production"

[context.branch-deploy]
  command = "hugo -s /opt/build/repo/zeroatthebone.us --gc --minify -D"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.161.1"
  NODE_VERSION="24.15.0"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/npmjs/*"
  to = "/npmjs/"
  status = 200