[build]
  command = "npm run build"
  publish = "zeroblog"

[context.deploy-preview]
  command = "npm run build-preview"

[context.production.environment]
  HUGO_VERSION = "0.58.3"

[context.deploy-previewn.environment]
  HUGO_VERSION = "0.58.3"
