name: link-checker

on: [ push ]

jobs:
  check-broken-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: 4thAce/action-hugo-link-check@v3-node24    
        with:
          hugo-startup-wait-time: 60
          hugo-root: zeroatthebone.us
          hugo-content-dir: zeroatthebone.us/content
          hugo-config: zeroatthebone.us/hugo.toml
          fail-on-broken-links: 0
          skip: 'http://localhost:1313//topics/*'